modLoader = "javafml"
loaderVersion = "[36.0,)"
license = "Apache-2.0"

[[mods]]
modId = "headintheclouds"
version = "${file.jarVersion}"
displayName = "Head In The Clouds"
authors = "Chloe Dawn"
description = '''Adjusts cloud height relative to the current altitude'''

[[dependencies.headintheclouds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
side = "CLIENT"

[[dependencies.headintheclouds]]
modId = "forge"
mandatory = true
versionRange = "[36.0,)"
side = "CLIENT"
